name:                im-thinking-of-a-number
version:             0.1.0.0
github:              "ctford/im-thinking-of-a-number"
license:             BSD3
author:              "Chris Ford"
maintainer:          "example@example.com"
copyright:           "2025 Chris Ford"

extra-source-files:
- README.md
- CLAUDE.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ctford/im-thinking-of-a-number#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- warp
- aeson
- stm
- transformers

library:
  source-dirs: src

executables:
  im-thinking-of-a-number-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - im-thinking-of-a-number

tests:
  im-thinking-of-a-number-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - im-thinking-of-a-number
    - hspec
    - servant-client